
create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

create table author
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country on delete cascade
);

create table shop_users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table book
(
    id               bigint generated by default as identity primary key,
    name             varchar(255),
    category         varchar(255), -- mapped from enum Category
    author_id        bigint references author on delete cascade,
    available_copies integer
);

create table wishlist
(
    id      bigint generated by default as identity primary key,
    user_id varchar(255) references shop_users(username),
    constraint uq_user_id unique (user_id)
);

create table wishlist_books
(
    wishlist_id bigint references wishlist on delete cascade,
    book_id     bigint references book on delete cascade,
    primary key (wishlist_id, book_id)
);

create index idx_user_role on shop_users(role);


INSERT INTO country (name, continent) VALUES
                                          ('country1', 'North America'),
                                          ('country2', 'Europe');


INSERT INTO author (name, surname, country_id) VALUES
                                                   ('Author1', 'Last1', 1),
                                                   ('Author2', 'Last2', 2);


INSERT INTO shop_users (username, password, name, surname, role) VALUES
                                                                                  ('lib', 'lib', 'lib', 'lib', 'ROLE_LIBRARIAN'),
                                                                                  ('user', 'user', 'user', 'user', 'ROLE_USER');


INSERT INTO book (name, category, author_id, available_copies) VALUES
                                                                   ('book1', 'NOVEL', 1, 10),
                                                                   ('book2', 'HISTORY', 1, 5),
                                                                   ('book3', 'FANTASY', 2, 8);


INSERT INTO wishlist (user_id) VALUES
                                   ('lib'),
                                   ('user');

INSERT INTO wishlist_books (wishlist_id, book_id) VALUES
                                                      (1, 1),
                                                      (2, 3);
